controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\TorreApiEndpont;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
//        return $this->render('index');
        if (isset($_SESSION['publicId'])) {

            return $this->render('index');

        } else {

            return $this->redirect(['login']);

        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $this->layout = 'loginlayout';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post())) {

            $endpoint = new TorreApiEndpont();

            $feedback = $endpoint->bio($model->username);

            if (!empty($feedback)) {
                \Yii::$app->session->set('publicId', $model->username);

                return $this->redirect('about');

            } else {

                return $this->render('login', [
                    'model' => $model,
                ]);
            }

        }

//        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionClosesearch()
    {
        unset($_SESSION['publicId']);
        return $this->redirect(['login']);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionOpportunity()
    {
        $endpoint = new TorreApiEndpont();

        $id = "0wxYeNd2";

        $opportunity = $endpoint->opportunity($id);

        if (!empty($opportunity)) {

            return $this->render('contact', [
                'opportunity' => $opportunity,
            ]);

        } else {

            Yii::$app->session->setFlash('Opportunity Not Available');

            return $this->redirect(['about']);
        }

    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        if (isset($_SESSION['publicId'])) {

            $endpoint = new TorreApiEndpont();

            $bio = $endpoint->bio($_SESSION['publicId']);

            return $this->render('about', [
                'bio' => $bio,
            ]);

        } else {

            return $this->redirect(['login']);

        }

    }
}

views/layouts/NavBar.php
<?php
/**
 * User: Kennedy Mukhwana Maikuma Lingo
 * Date: 6/24/2020
 * Time: 5:42 PM
 */

use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

?>
    <nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-brand">
                Torre
                <!--                <a href="index.html"><img src="../assets/images/logo.svg" alt="Lucid Logo" class="img-responsive logo"></a>-->
            </div>
            <div class="navbar-right">
                <div id="navbar-menu">
                    <?php
                    NavBar::begin([
                        'options' => [
                            'class' => 'nav navbar-nav',
                        ],
                    ]);

                    echo Nav::widget([
//                        'options' => ['class' => 'nav navbar-nav'],
                        'items' => [
//                            ['label' => 'Home', 'url' => ['/site/index']],
                            ['label' => 'Bio', 'url' => ['/site/about']],
                            ['label' => 'Opportunity Sample', 'url' => ['/site/opportunity']],
                            isset($_SESSION['publicId']) ? (
                            ['label' => 'Logout (' . \Yii::$app->session->get('publicId') . ') ', 'url' => ['/site/closesearch']]
//                    '<li>'
//
//                . Html::beginForm(['/site/logout'], 'post')
//                . Html::submitButton(
//                    'Logout (' . \Yii::$app->session->get('publicId'). ')',
//                    ['class' => 'btn btn-link logout']
//                )
//                . Html::endForm()
//                . '</li>'
                            ) : (['label' => 'Login', 'url' => ['/site/login']])

//            Yii::$app->user->isGuest ? (
//                ['label' => 'Login', 'url' => ['/site/login']]
//            ) : (
//                '<li>'
//                . Html::beginForm(['/site/logout'], 'post')
//                . Html::submitButton(
//                    'Logout (' . Yii::$app->user->identity->username . ')',
//                    ['class' => 'btn btn-link logout']
//                )
//                . Html::endForm()
//                . '</li>'
//            )
                        ],
                    ]);
                    NavBar::end();
                    ?>
                </div>
            </div>

        </div>
    </nav>

views/layouts/loginlayout.php
<?php
/**
 * User: Kennedy Mukhwana Maikuma Lingo
 * Date: 6/24/2020
 * Time: 5:04 PM
 */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
// get the layout(Css and Js) for the page
use app\assets\LoginAsset;

LoginAsset::register($this);

//Page Begins
$this->beginPage();
?>
<!doctype html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="description" content="Lucid Bootstrap 4.1.1 Admin Template">
    <meta name="author" content="WrapTheme, design by: ThemeMakker.com">

    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

</head>
<body class="theme-blue">
<?php $this->beginBody() ?>
<!-- WRAPPER -->
<div id="wrapper">
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle auth-main">
            <div class="auth-box">
                <div class="top">
                    Torre
                </div>
                <div class="card">
                    <div class="header">
                        <p class="lead">Login to your account</p>
                    </div>
                    <div class="body">
                        <?= Alert::widget() ?>
                        <?= $content ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END WRAPPER -->

<!-- Javascript -->

<!-- </body> -->
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div id="wrapper">
    <?= $this->render('NavBar.php'); ?>
    <div id="main-content">
        <div class="container">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-6 col-md-8 col-sm-12">
                        <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i
                                        class="fa fa-arrow-left"></i></a> <?= $this->title ?></h2>
                        <!--                        <ul class="breadcrumb">-->
                        <!--                            <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>-->
                        <!--                            <li class="breadcrumb-item">Pages</li>-->
                        <!--                            <li class="breadcrumb-item active">Page Blank</li>-->
                        <!--                        </ul>-->
                        <?= Breadcrumbs::widget([
                            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                        ]) ?>
                    </div>
                    <div class="col-lg-6 col-md-4 col-sm-12 text-right">

                    </div>
                </div>
            </div>
            <!--  Main Content Page-->

            <?= $content ?>

        </div>
    </div>

</div>


<!--<footer class="footer">-->
<!--    <div class="container">-->
<!--        <p class="pull-left">&copy; My Company --><? //= date('Y') ?><!--</p>-->
<!---->
<!--        <p class="pull-right">--><? //= Yii::powered() ?><!--</p>-->
<!--    </div>-->
<!--</footer>-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>